<?php

$publicKey = $this->getPublicKey();

if ($this->isActive() && $publicKey){
	
	echo
		'<script type="text/javascript" src="https://static.leaddyno.com/js"></script>',
		'<script type="text/javascript">/*<![CDATA[*/',
			'LeadDyno.domain="', $this->getHost(), '";',
			'LeadDyno.key="', $publicKey, '";',
			'LeadDyno.recordVisit();';
			
			if ($this->isWatcherActive()){
				
				$watcherSelector = $this->getWatcherSelector();
				if (!$watcherSelector)
					echo 'LeadDyno.autoWatch();';
				else
					echo 'LeadDyno.watch("', $watcherSelector, '");';
				
			}
			
	echo
		'//]]></script>';
	
}